# Generated by Django 2.0.2 on 2019-01-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('surname', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('desc', models.CharField(max_length=128, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, max_length=512, upload_to='news/medium', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'О себе',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('image', models.ImageField(blank=True, max_length=512, upload_to='news/medium', verbose_name='Изображение')),
                ('desc', models.CharField(max_length=128, verbose_name='Описание')),
                ('pdf_file', models.FileField(blank=True, upload_to='news/medium')),
            ],
            options={
                'verbose_name': 'Проекты',
            },
        ),
    ]
