# Generated by Django 2.0.2 on 2019-01-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О себе', 'verbose_name_plural': 'О себе'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проекты', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='about',
            name='job',
            field=models.CharField(blank=True, max_length=128, verbose_name='Профессия'),
        ),
    ]
