# Generated by Django 2.0.2 on 2019-01-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20190121_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='desc',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
